/**
 * Pipeline V2 Types - Vertical Slice Sequential Execution
 *
 * This is a fundamentally different approach from the existing theme-based
 * parallel execution model (planning-types.ts). Key differences:
 *
 * - Sequential execution: Single container, persona hot-swap per step
 * - Git commit history IS the state machine
 * - Built-in TDD with verification types per step
 * - Plan Repair and Smart Rewind on failure
 * - Critic Agent validates plans before execution
 * - Simpler status model: planning → executing → done/failed
 *
 * Triggered by `prd-v2` Jira label for opt-in gradual rollout.
 */

import { WorkerPersona } from "../models/WorkerTask.js";

// ============================================================================
// TECH STACK (reused from existing planning)
// ============================================================================

/**
 * Tech stack decisions for the project.
 * Determines template selection for Step 0.
 */
export interface TechStackV2 {
  /** Primary language (typescript, python, javascript, go) */
  language: string;
  /** Framework (react, fastapi, express, nextjs) */
  framework: string;
  /** Styling approach (tailwind, css-modules, vanilla-css) */
  styling?: string;
  /** Database (postgresql, mongodb, sqlite, none) */
  database?: string;
  /** Testing framework (vitest, jest, pytest) */
  testing?: string;
  /** Build tool (vite, webpack, esbuild) */
  buildTool?: string;
  /** Template ID for Step 0 injection */
  templateId?: "react-vite-typescript" | "fastapi-python" | "express-typescript" | "nextjs-typescript" | null;
  /** Rationale for tech choices */
  rationale: string;
  /** PRD constraints that must be preserved */
  prdConstraints?: string[];
}

// ============================================================================
// VERIFICATION TYPES
// ============================================================================

/**
 * Verification strategy for each step based on content type.
 * Determines how the step's success is validated before committing.
 */
export type VerificationType = "logic" | "ui" | "docs" | "config";

/**
 * Verification strategies by type
 */
export const VERIFICATION_STRATEGIES: Record<VerificationType, string> = {
  logic: "Strict TDD: Write failing test → Implement → Test passes",
  ui: "Structural: Build passes, component mounts, snapshot test",
  docs: "Linting: Markdown lint, link validation",
  config: "Validation: Config parses, no syntax errors",
};

// ============================================================================
// PLANNED STEP
// ============================================================================

/**
 * A single atomic step in the execution plan.
 * Each step is executed sequentially, commits on success.
 */
export interface PlannedStepV2 {
  /** Step index (0-based) */
  index: number;

  /** Short title describing the step */
  title: string;

  /** Detailed description of what needs to be done */
  description: string;

  /** Worker persona to use for this step */
  persona: WorkerPersona;

  /** How to verify this step completed successfully */
  verificationType: VerificationType;

  /** Specific verification instructions for the worker */
  verificationInstructions: string;

  /** Files this step will create or modify (max 3 for focus) */
  targetFiles: string[];

  /**
   * Files to read for context/patterns (not modified).
   *
   * Supports glob patterns for files that may not exist at planning time:
   * - Exact paths: "src/auth/Login.tsx"
   * - Wildcards: "src/**\/auth*.ts"
   * - Descriptions: "[the main auth module]"
   *
   * The Runner resolves these to actual paths before step execution.
   * If a pattern matches nothing, the agent will be instructed to find
   * the file itself using the description.
   */
  referenceFiles?: string[];

  /** Estimated complexity (1-3 scale) */
  estimatedComplexity?: 1 | 2 | 3;

  /** Timeout for this step in minutes (default: 15) */
  timeoutMinutes?: number;
}

/**
 * Default timeout per step in minutes
 */
export const DEFAULT_STEP_TIMEOUT_MINUTES = 15;

/**
 * Get effective timeout for a step
 */
export function getStepTimeout(step: PlannedStepV2): number {
  return (step.timeoutMinutes ?? DEFAULT_STEP_TIMEOUT_MINUTES) * 60 * 1000;
}

// ============================================================================
// EXECUTION PLAN V2
// ============================================================================

/**
 * Complete execution plan for vertical slice sequential execution.
 * Generated by Planner Agent, validated by Critic Agent.
 */
export interface ExecutionPlanV2 {
  /** Plan version identifier */
  version: 3; // Using 3 since V2 exists in planning-types.ts

  /** High-level summary of the architecture approach */
  architecturalSummary: string;

  /** Tech stack decisions for this project */
  techStack: TechStackV2;

  /** Ordered list of atomic execution steps */
  steps: PlannedStepV2[];

  /** Critic Agent's confidence score (0-100) */
  criticScore?: number;

  /** Critic Agent's identified risks */
  criticRisks?: string[];

  /** Planning metadata */
  metadata?: PlanningMetadataV2;
}

/**
 * Metadata tracked during plan generation
 */
export interface PlanningMetadataV2 {
  /** Total LLM calls made during planning */
  llmCalls: number;

  /** Time spent planning (ms) */
  planningDurationMs: number;

  /** Model used for plan generation */
  plannerModel: string;

  /** Model used for plan validation */
  criticModel: string;

  /** Number of Planner-Critic iterations */
  iterationCount: number;

  /** Was the plan auto-approved or human-approved */
  approvalMethod?: "auto" | "human";

  /** Timestamp of plan generation */
  generatedAt: string;
}

// ============================================================================
// CRITIC AGENT TYPES
// ============================================================================

/**
 * Result from Critic Agent plan validation
 */
export interface CriticResult {
  /** Whether the plan is approved */
  approved: boolean;

  /** Confidence score (0-100) */
  score: number;

  /** Identified risks and issues */
  risks: string[];

  /** Suggestions for improvement */
  suggestions?: string[];

  /** Model used for validation */
  model: string;
}

// ============================================================================
// STEP EXECUTION TYPES
// ============================================================================

/**
 * Input provided to worker for step execution
 */
export interface WorkerStepInput {
  /** The step to execute */
  step: PlannedStepV2;

  /** Accumulated constraints from previous failures/rewinds */
  contextSidecar: string[];

  /** Commit hash to restore to (for rewind scenarios) */
  previousCommitHash?: string;

  /** How to handle repo state */
  repoState: "fresh" | "continue" | "rewind";

  /**
   * Git command to run before step execution.
   * For rewinds: `git reset --hard <hash> && git clean -fd`
   * For fresh: `git clean -fd`
   * For continue: undefined (no cleanup needed)
   *
   * IMPORTANT: Always includes `git clean -fd` to remove ghost files.
   */
  gitSetupCommand?: string;

  /** Full execution plan for context */
  fullPlan: ExecutionPlanV2;

  /** Current step index in the overall pipeline */
  currentStepIndex: number;

  /** Total number of steps */
  totalSteps: number;

  /**
   * Resolved reference file paths (wildcards expanded).
   * Populated by the worker after glob resolution.
   */
  resolvedReferenceFiles?: string[];

  /**
   * Instructions for agent to find files that couldn't be resolved.
   * E.g., "Find files matching pattern: src/**\/auth*.ts"
   * Populated by the worker when patterns don't match anything.
   */
  unresolvedReferenceInstructions?: string[];
}

/**
 * Result reported by worker after step execution
 */
export interface WorkerStepResult {
  /** Step completion status */
  status: "STEP_COMPLETE" | "STEP_FAILED" | "NEEDS_REWIND";

  /** Git commit hash if step succeeded */
  commitHash?: string;

  /** Execution logs */
  logs: string;

  /** New constraints learned from this step (especially on failure) */
  suggestedConstraints?: string[];

  /** If rewind needed, which step index to rewind to */
  rewindSuggestion?: number;

  /** Error details if failed */
  errorMessage?: string;

  /** Token usage for this step */
  tokenUsage?: {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens?: number;
    cacheCreationTokens?: number;
  };
}

// ============================================================================
// COMMIT HISTORY
// ============================================================================

/**
 * Record of a successful step commit
 */
export interface StepCommit {
  /** Step index that was completed */
  stepIndex: number;

  /** Git commit hash */
  commitHash: string;

  /** Persona that executed the step */
  persona: WorkerPersona;

  /** Timestamp of commit */
  committedAt: string;

  /** Duration of step execution (ms) */
  durationMs?: number;
}

// ============================================================================
// PLAN REPAIR TYPES
// ============================================================================

/**
 * Decision from Planner when recovering from step failure
 */
export interface RecoveryDecision {
  /** Recovery action to take */
  action: "RETRY_STEP" | "RETRY_WITH_MODIFIED_STEP" | "REWIND" | "ESCALATE";

  /** Modified step for RETRY_WITH_MODIFIED_STEP */
  modifiedStep?: PlannedStepV2;

  /** Target step index for REWIND */
  targetStepIndex?: number;

  /** Target commit hash for REWIND */
  targetCommitHash?: string;

  /** New constraint to add to context sidecar */
  newConstraint?: string;

  /** Reason for escalation */
  reason?: string;
}

/**
 * Input for recovery decision
 */
export interface RecoveryInput {
  /** Error logs from failed step */
  errorLogs: string;

  /** The step that failed */
  currentStep: PlannedStepV2;

  /** All commits so far */
  commitHistory: StepCommit[];

  /** Current context sidecar */
  contextSidecar: string[];

  /** Number of retries on current step */
  currentStepRetryCount: number;
}

// ============================================================================
// REWIND THRESHOLDS & COMMANDS
// ============================================================================

/**
 * Rewind threshold configuration
 * If exceeded, escalate to human instead of automatic rewind
 */
export const REWIND_THRESHOLDS = {
  /** Max steps to rewind before escalating */
  maxStepsToRewind: 2,
  /** Max percentage of completed steps to rewind */
  maxPercentageToRewind: 0.2,
  /** Max retries per step before considering rewind */
  maxRetriesPerStep: 3,
};

/**
 * Git command for rewind operations.
 *
 * CRITICAL: Must use both `git reset --hard` AND `git clean -fd`
 *
 * - `git reset --hard` moves HEAD and resets tracked files
 * - `git clean -fd` removes untracked files/directories created by the failed step
 *
 * Without git clean, "ghost files" from failed steps can confuse subsequent attempts.
 */
export const REWIND_GIT_COMMAND = (commitHash: string) =>
  `git reset --hard ${commitHash} && git clean -fd`;

/**
 * Git command for fresh start (no previous commits)
 */
export const FRESH_START_GIT_COMMAND = "git clean -fd";

// ============================================================================
// PIPELINE STATE
// ============================================================================

/**
 * V2 Pipeline status (simplified from V1's 15+ statuses)
 */
export type PipelineV2Status = "planning" | "executing" | "done" | "failed";

/**
 * Fields stored on WorkerTask for V2 pipeline tracking
 */
export interface PipelineV2Fields {
  /** The execution plan */
  executionPlanV2: ExecutionPlanV2 | null;

  /** Current step being executed (0-based) */
  currentStepIndex: number;

  /** Learned constraints outside of git */
  contextSidecar: string[];

  /** History of successful step commits */
  commitHistory: StepCommit[];

  /** Retry count for current step */
  currentStepRetryCount: number;

  /** Pipeline version flag */
  pipelineVersion: "v1" | "v2" | null;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Check if a task is using V2 pipeline
 */
export function isV2Pipeline(task: { pipelineVersion?: string | null }): boolean {
  return task.pipelineVersion === "v2";
}

/**
 * Check if a rewind would exceed thresholds
 */
export function wouldExceedRewindThreshold(
  currentStepIndex: number,
  targetStepIndex: number,
  totalSteps: number,
): boolean {
  const stepsToRewind = currentStepIndex - targetStepIndex;

  // Check absolute step limit
  if (stepsToRewind > REWIND_THRESHOLDS.maxStepsToRewind) {
    return true;
  }

  // Check percentage limit (only if we have significant progress)
  if (totalSteps > 5) {
    const percentageToRewind = stepsToRewind / currentStepIndex;
    if (percentageToRewind > REWIND_THRESHOLDS.maxPercentageToRewind) {
      return true;
    }
  }

  return false;
}

/**
 * Get the template ID based on tech stack
 */
export function getTemplateId(techStack: TechStackV2): TechStackV2["templateId"] {
  // Explicit template ID takes precedence
  if (techStack.templateId) {
    return techStack.templateId;
  }

  // Infer from framework and language
  const { framework, language } = techStack;

  if (framework === "react" && techStack.buildTool === "vite" && language === "typescript") {
    return "react-vite-typescript";
  }
  if (framework === "fastapi" && language === "python") {
    return "fastapi-python";
  }
  if (framework === "express" && language === "typescript") {
    return "express-typescript";
  }
  if (framework === "nextjs" && language === "typescript") {
    return "nextjs-typescript";
  }

  // No matching template
  return null;
}

/**
 * Calculate overall pipeline progress percentage
 */
export function calculateProgress(currentStepIndex: number, totalSteps: number): number {
  if (totalSteps === 0) return 0;
  return Math.round((currentStepIndex / totalSteps) * 100);
}

// ============================================================================
// REFERENCE FILE RESOLUTION
// ============================================================================

/**
 * Reference file resolution happens in the WORKER, not the API.
 *
 * Why: The API doesn't have access to the cloned repo filesystem.
 * The worker runs the following resolution logic before step execution:
 *
 * 1. For exact paths: verify file exists, add to resolved list
 * 2. For glob patterns: expand using fast-glob, add matches to resolved list
 * 3. For descriptions: add to unresolved instructions for agent to find
 *
 * The worker passes both `resolvedReferenceFiles` (actual paths) and
 * `unresolvedReferenceInstructions` (agent search tasks) to Claude.
 */

/**
 * Classify a reference file entry as exact path, glob pattern, or description.
 */
export function classifyReferenceFile(ref: string): "exact" | "glob" | "description" {
  // Descriptions are wrapped in brackets: [the main auth module]
  if (ref.startsWith("[") && ref.endsWith("]")) {
    return "description";
  }
  // Glob patterns contain wildcards
  if (ref.includes("*") || ref.includes("?") || ref.includes("{")) {
    return "glob";
  }
  // Otherwise it's an exact path
  return "exact";
}

/**
 * Resolved reference file with metadata about how it was resolved.
 */
export interface ResolvedReferenceFile {
  /** Original pattern/path from the plan */
  original: string;
  /** How it was classified */
  type: "exact" | "glob" | "description";
  /** Resolved file path(s), or null if unresolved */
  resolved: string[] | null;
  /** If unresolved, instruction for the agent */
  instruction?: string;
}

/**
 * Result of reference file resolution.
 */
export interface ReferenceFileResolution {
  /** Successfully resolved file paths */
  resolvedPaths: string[];
  /** Unresolved patterns with instructions for the agent */
  unresolvedInstructions: string[];
  /** Full resolution details for logging */
  details: ResolvedReferenceFile[];
}

/**
 * Build agent instructions for unresolved reference files.
 * Called when a pattern/description couldn't be resolved at runtime.
 */
export function buildUnresolvedInstruction(ref: string, type: "glob" | "description"): string {
  if (type === "description") {
    // Strip brackets from description
    const description = ref.slice(1, -1);
    return `Find the file matching this description: "${description}"`;
  }
  // Glob pattern
  return `Find files matching pattern: ${ref}`;
}
