import { AppDataSource } from "../db/connection.js";
import { KbSpecTemplate } from "../models/index.js";
import { logger } from "../utils/logger.js";

interface BuiltInTemplate {
  name: string;
  description: string;
  content: string;
  requiredSections: string[];
}

const BUILT_IN_TEMPLATES: BuiltInTemplate[] = [
  {
    name: "SaaS Web App",
    description:
      "Full-stack web application with database, API, and frontend",
    requiredSections: [
      "overview",
      "technical_spec",
      "data_model",
      "file_structure",
      "api_spec",
      "components",
      "quality_gates",
      "acceptance_criteria",
      "scope_boundary",
    ],
    content: `***REMOVED*** [Project Name] — Full Build Specification

***REMOVED******REMOVED*** Overview

<!-- Describe what this project builds. List 8-12 deliverables as numbered items. -->
<!-- Example: -->
<!-- 1. User authentication (email/password + OAuth) -->
<!-- 2. Dashboard with data visualization -->
<!-- 3. REST API with CRUD operations -->

**Deliverables:**

1. [Deliverable 1]
2. [Deliverable 2]
3. [Deliverable 3]

---

***REMOVED******REMOVED*** Technical Specification

***REMOVED******REMOVED******REMOVED*** Version Constraints (MUST follow exactly)

<!-- Pin ALL major dependency versions. This prevents the AI from using outdated or incompatible versions. -->

\`\`\`json
{
  "engines": { "node": ">=20.0.0" },
  "dependencies": {
    "framework": "^x.y.z",
    "database-client": "^x.y.z",
    "auth-library": "^x.y.z"
  },
  "devDependencies": {
    "typescript": "^5.7.0",
    "test-framework": "^x.y.z",
    "linter": "^x.y.z"
  }
}
\`\`\`

***REMOVED******REMOVED******REMOVED*** Architecture Patterns

<!-- Describe key patterns: server components vs client components, data fetching strategy, auth flow, etc. -->

---

***REMOVED******REMOVED*** Data Model

<!-- Define your complete database schema. Use Prisma, SQL, or TypeORM entity format. -->
<!-- Include ALL models, enums, and relationships. -->

\`\`\`prisma
// Example:
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
}
\`\`\`

---

***REMOVED******REMOVED*** File Structure

<!-- Define the exact directory structure. This prevents the AI from inventing its own layout. -->

\`\`\`
project-name/
├── src/
│   ├── app/                    ***REMOVED*** Routes and pages
│   ├── components/             ***REMOVED*** Reusable UI components
│   ├── lib/                    ***REMOVED*** Utilities and helpers
│   └── types/                  ***REMOVED*** TypeScript types
├── tests/
│   └── unit/
├── .github/workflows/
│   └── ci.yml
├── package.json
└── tsconfig.json
\`\`\`

---

***REMOVED******REMOVED*** API Specification

<!-- Define every API endpoint with method, path, request body, and response shape. -->

| Method | Path | Description | Request Body | Response |
|--------|------|-------------|-------------|----------|
| GET | /api/resource | List resources | — | \`{ data: Resource[] }\` |
| POST | /api/resource | Create resource | \`{ name, ... }\` | \`{ data: Resource }\` |

---

***REMOVED******REMOVED*** Component Specification

<!-- Define key UI components with their props and behavior. -->

| Component | Props | Behavior |
|-----------|-------|----------|
| ResourceList | \`{ items: Resource[] }\` | Renders paginated list with search |

---

***REMOVED******REMOVED*** Quality Gates

<!-- Define the commands that must pass before code is committed. -->

\`\`\`bash
npm run lint
npm run typecheck
npm run test
npm run build
\`\`\`

---

***REMOVED******REMOVED*** Acceptance Criteria

<!-- Define measurable success conditions. Each must be verifiable by a machine or human. -->

- [ ] All quality gate commands pass
- [ ] Application builds and deploys successfully
- [ ] Core user flows work end-to-end
- [ ] All API endpoints return correct response shapes

---

***REMOVED******REMOVED*** Scope Boundary

<!-- CRITICAL: Define what the AI should NOT build. This prevents scope creep. -->

**DO NOT create:**
- Payment/billing integration
- Email notification system
- Admin panel
- Mobile app
- Analytics/tracking
- Documentation website

---

***REMOVED******REMOVED*** Pre-Provisioned Infrastructure

<!-- List resources that already exist and should be used, not created. -->

| Resource | Value |
|----------|-------|
| Repository | \`org/project-name\` |
| Database | [connection details in env vars] |
| Hosting | [platform and project details] |

---

***REMOVED******REMOVED*** Worker Stories

<!-- Stories will be auto-generated by the decomposer. You can optionally pre-define them here. -->
`,
  },
  {
    name: "API Service",
    description:
      "Backend API with endpoints, authentication, and data models",
    requiredSections: [
      "overview",
      "technical_spec",
      "data_model",
      "api_spec",
      "quality_gates",
      "acceptance_criteria",
      "scope_boundary",
    ],
    content: `***REMOVED*** [Service Name] — API Specification

***REMOVED******REMOVED*** Overview

<!-- Describe what this API service does. List 5-8 deliverables. -->

**Deliverables:**

1. [Endpoint group 1]
2. [Endpoint group 2]
3. Authentication and authorization
4. Error handling and validation
5. CI/CD pipeline

---

***REMOVED******REMOVED*** Technical Specification

***REMOVED******REMOVED******REMOVED*** Version Constraints

\`\`\`json
{
  "engines": { "node": ">=20.0.0" },
  "dependencies": {
    "express": "^4.21.0",
    "typeorm": "^0.3.20",
    "zod": "^3.23.0",
    "jsonwebtoken": "^9.0.0"
  },
  "devDependencies": {
    "typescript": "^5.7.0",
    "vitest": "^2.1.0",
    "eslint": "^9.0.0"
  }
}
\`\`\`

***REMOVED******REMOVED******REMOVED*** Architecture

<!-- API architecture: middleware stack, auth strategy, error handling pattern, logging. -->

---

***REMOVED******REMOVED*** Data Model

<!-- Complete database schema with all tables, columns, types, constraints, and relationships. -->

\`\`\`sql
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
\`\`\`

---

***REMOVED******REMOVED*** API Endpoints

<!-- Every endpoint with method, path, auth requirement, request/response shapes, and error codes. -->

***REMOVED******REMOVED******REMOVED*** Authentication

| Method | Path | Auth | Description |
|--------|------|------|-------------|
| POST | /api/auth/login | None | Login with email/password |
| POST | /api/auth/register | None | Create account |

***REMOVED******REMOVED******REMOVED*** Resources

| Method | Path | Auth | Description |
|--------|------|------|-------------|
| GET | /api/resources | JWT | List resources |
| POST | /api/resources | JWT | Create resource |
| GET | /api/resources/:id | JWT | Get single resource |
| PUT | /api/resources/:id | JWT | Update resource |
| DELETE | /api/resources/:id | JWT | Delete resource |

***REMOVED******REMOVED******REMOVED*** Error Responses

\`\`\`json
{ "error": "message", "code": "ERROR_CODE" }
\`\`\`

| Status | Code | Description |
|--------|------|-------------|
| 400 | VALIDATION_ERROR | Request body failed validation |
| 401 | UNAUTHORIZED | Missing or invalid token |
| 404 | NOT_FOUND | Resource not found |

---

***REMOVED******REMOVED*** Quality Gates

\`\`\`bash
npm run lint
npm run typecheck
npm run test
npm run build
\`\`\`

---

***REMOVED******REMOVED*** Acceptance Criteria

- [ ] All endpoints return correct status codes and response shapes
- [ ] Authentication works (login, register, protected routes)
- [ ] Validation rejects invalid input with helpful error messages
- [ ] All quality gates pass
- [ ] API can be deployed and health check returns 200

---

***REMOVED******REMOVED*** Scope Boundary

**DO NOT create:**
- Frontend/UI
- WebSocket connections
- File upload handling
- Rate limiting
- API documentation (Swagger/OpenAPI)
`,
  },
  {
    name: "CLI Tool",
    description:
      "Command-line application with commands, flags, and configuration",
    requiredSections: [
      "overview",
      "technical_spec",
      "commands",
      "quality_gates",
      "acceptance_criteria",
      "scope_boundary",
    ],
    content: `***REMOVED*** [Tool Name] — CLI Specification

***REMOVED******REMOVED*** Overview

<!-- Describe what this CLI tool does. List the main commands and their purpose. -->

**Deliverables:**

1. CLI entry point with argument parsing
2. [Command 1]
3. [Command 2]
4. Configuration file support
5. Help text and documentation
6. Test suite

---

***REMOVED******REMOVED*** Technical Specification

***REMOVED******REMOVED******REMOVED*** Version Constraints

\`\`\`json
{
  "engines": { "node": ">=20.0.0" },
  "dependencies": {
    "commander": "^12.0.0"
  },
  "devDependencies": {
    "typescript": "^5.7.0",
    "vitest": "^2.1.0",
    "esbuild": "^0.24.0"
  }
}
\`\`\`

***REMOVED******REMOVED******REMOVED*** Distribution

<!-- How the CLI will be distributed: npm global install, standalone binary, etc. -->

---

***REMOVED******REMOVED*** Commands

<!-- Define every command with its flags, arguments, and behavior. -->

***REMOVED******REMOVED******REMOVED*** \`tool-name init\`

Initialize a new project.

| Flag | Type | Default | Description |
|------|------|---------|-------------|
| --name | string | (required) | Project name |
| --template | string | "default" | Template to use |
| --force | boolean | false | Overwrite existing |

**Behavior:**
1. Check if directory exists
2. Create project structure
3. Write configuration file
4. Print success message

**Exit codes:** 0 = success, 1 = error

***REMOVED******REMOVED******REMOVED*** \`tool-name run\`

Run the main operation.

| Flag | Type | Default | Description |
|------|------|---------|-------------|
| --config | string | "./config.json" | Config file path |
| --verbose | boolean | false | Enable verbose output |

---

***REMOVED******REMOVED*** Configuration

\`\`\`json
{
  "name": "project-name",
  "version": "1.0.0",
  "options": {}
}
\`\`\`

---

***REMOVED******REMOVED*** Quality Gates

\`\`\`bash
npm run lint
npm run typecheck
npm run test
npm run build
\`\`\`

---

***REMOVED******REMOVED*** Acceptance Criteria

- [ ] All commands execute correctly with valid input
- [ ] Invalid input shows helpful error messages
- [ ] --help flag works for all commands
- [ ] Configuration file is read and applied correctly
- [ ] Exit codes are correct (0 for success, 1 for error)
- [ ] All quality gates pass

---

***REMOVED******REMOVED*** Scope Boundary

**DO NOT create:**
- GUI/web interface
- Interactive prompts (use flags only)
- Plugin system
- Auto-update mechanism
`,
  },
  {
    name: "Mobile App",
    description: "React Native or Flutter mobile application",
    requiredSections: [
      "overview",
      "technical_spec",
      "screens",
      "data_model",
      "quality_gates",
      "acceptance_criteria",
      "scope_boundary",
    ],
    content: `***REMOVED*** [App Name] — Mobile App Specification

***REMOVED******REMOVED*** Overview

<!-- Describe what this mobile app does. List 6-10 screens/features. -->

**Deliverables:**

1. Authentication flow (login, signup, forgot password)
2. [Main screen 1]
3. [Main screen 2]
4. Navigation structure (tab bar + stack navigation)
5. State management
6. API integration

---

***REMOVED******REMOVED*** Technical Specification

***REMOVED******REMOVED******REMOVED*** Version Constraints

\`\`\`json
{
  "dependencies": {
    "react-native": "^0.76.0",
    "react": "^19.0.0",
    "@react-navigation/native": "^7.0.0",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "zustand": "^5.0.0"
  },
  "devDependencies": {
    "typescript": "^5.7.0",
    "jest": "^29.0.0",
    "@testing-library/react-native": "^12.0.0"
  }
}
\`\`\`

***REMOVED******REMOVED******REMOVED*** Platform Support

- iOS 16+
- Android 13+ (API level 33)

---

***REMOVED******REMOVED*** Screens & Navigation

<!-- Define every screen with its purpose, data requirements, and navigation behavior. -->

***REMOVED******REMOVED******REMOVED*** Navigation Structure

\`\`\`
TabNavigator
├── HomeStack
│   ├── HomeScreen
│   └── DetailScreen
├── SearchStack
│   └── SearchScreen
└── ProfileStack
    ├── ProfileScreen
    └── SettingsScreen
\`\`\`

***REMOVED******REMOVED******REMOVED*** Screen Definitions

| Screen | Type | Data | Actions |
|--------|------|------|---------|
| HomeScreen | Tab | List of items | Pull to refresh, tap to detail |
| DetailScreen | Stack | Single item | Edit, delete, share |
| ProfileScreen | Tab | User profile | Edit profile, logout |

---

***REMOVED******REMOVED*** Data Model

<!-- Define the data structures used in the app. -->

\`\`\`typescript
interface User {
  id: string;
  email: string;
  name: string;
  avatarUrl: string | null;
}
\`\`\`

---

***REMOVED******REMOVED*** Quality Gates

\`\`\`bash
npm run lint
npm run typecheck
npm run test
npx react-native build-android --mode=release
\`\`\`

---

***REMOVED******REMOVED*** Acceptance Criteria

- [ ] All screens render correctly on iOS and Android
- [ ] Navigation works between all screens
- [ ] Authentication flow works end-to-end
- [ ] Data loads and displays correctly
- [ ] Pull-to-refresh works on list screens
- [ ] All quality gates pass

---

***REMOVED******REMOVED*** Scope Boundary

**DO NOT create:**
- Push notifications
- In-app purchases
- Offline mode / local database
- Deep linking
- App Store / Play Store assets
- Analytics/crash reporting
`,
  },
];

/**
 * Ensures built-in templates exist in the database.
 * Idempotent — checks by name before inserting.
 * Called lazily on first template list access.
 */
export async function ensureBuiltInTemplates(orgId: string): Promise<void> {
  const repo = AppDataSource.getRepository(KbSpecTemplate);

  // Check if any public templates exist
  const existingCount = await repo.count({ where: { isPublic: true } });
  if (existingCount >= BUILT_IN_TEMPLATES.length) {
    return; // Already seeded
  }

  for (const tmpl of BUILT_IN_TEMPLATES) {
    const existing = await repo.findOne({
      where: { name: tmpl.name, isPublic: true },
    });
    if (!existing) {
      await repo.save(
        repo.create({
          orgId,
          name: tmpl.name,
          description: tmpl.description,
          content: tmpl.content,
          requiredSections: tmpl.requiredSections,
          isDefault: false,
          isPublic: true,
        }),
      );
      logger.info("Created built-in spec template", { name: tmpl.name });
    }
  }
}
