/**
 * Frontend types for Pipeline V2 - Vertical Slice Sequential Execution
 * Mirrors backend api/src/services/pipeline-v2-types.ts for UI display
 */

import type { WorkerPersona } from "./mission-control";

// ============================================================================
// VERIFICATION TYPES
// ============================================================================

/**
 * Verification strategy for each step based on content type.
 * Determines how the step's success is validated before committing.
 */
export type VerificationType = "logic" | "ui" | "docs" | "config";

/**
 * Verification strategies by type for display
 */
export const VERIFICATION_STRATEGIES: Record<VerificationType, string> = {
  logic: "Strict TDD: Write failing test -> Implement -> Test passes",
  ui: "Structural: Build passes, component mounts, snapshot test",
  docs: "Linting: Markdown lint, link validation",
  config: "Validation: Config parses, no syntax errors",
};

/**
 * Colors for verification type display
 */
export const VERIFICATION_COLORS: Record<VerificationType, string> = {
  logic: "text-purple-500",
  ui: "text-blue-500",
  docs: "text-green-500",
  config: "text-yellow-500",
};

// ============================================================================
// TECH STACK
// ============================================================================

/**
 * Tech stack decisions for the project.
 */
export interface TechStackV2 {
  /** Primary language (typescript, python, javascript, go) */
  language: string;
  /** Framework (react, fastapi, express, nextjs) */
  framework: string;
  /** Styling approach (tailwind, css-modules, vanilla-css) */
  styling?: string;
  /** Database (postgresql, mongodb, sqlite, none) */
  database?: string;
  /** Testing framework (vitest, jest, pytest) */
  testing?: string;
  /** Build tool (vite, webpack, esbuild) */
  buildTool?: string;
  /** Template ID for Step 0 injection */
  templateId?: "react-vite-typescript" | "fastapi-python" | "express-typescript" | "nextjs-typescript" | null;
  /** Rationale for tech choices */
  rationale: string;
  /** PRD constraints that must be preserved */
  prdConstraints?: string[];
}

// ============================================================================
// PLANNED STEP
// ============================================================================

/**
 * A single atomic step in the execution plan.
 * Each step is executed sequentially, commits on success.
 */
export interface PlannedStepV2 {
  /** Step index (0-based) */
  index: number;

  /** Short title describing the step */
  title: string;

  /** Detailed description of what needs to be done */
  description: string;

  /** Worker persona to use for this step */
  persona: WorkerPersona;

  /** How to verify this step completed successfully */
  verificationType: VerificationType;

  /** Specific verification instructions for the worker */
  verificationInstructions: string;

  /** Files this step will create or modify (max 3 for focus) */
  targetFiles: string[];

  /** Files to read for context/patterns (not modified) */
  referenceFiles?: string[];

  /** Estimated complexity (1-3 scale) */
  estimatedComplexity?: 1 | 2 | 3;
}

// ============================================================================
// EXECUTION PLAN V2
// ============================================================================

/**
 * Planning metadata tracked during plan generation
 */
export interface PlanningMetadataV2 {
  /** Total LLM calls made during planning */
  llmCalls: number;

  /** Time spent planning (ms) */
  planningDurationMs: number;

  /** Model used for plan generation */
  plannerModel: string;

  /** Model used for plan validation */
  criticModel: string;

  /** Number of Planner-Critic iterations */
  iterationCount: number;

  /** Was the plan auto-approved or human-approved */
  approvalMethod?: "auto" | "human";

  /** Timestamp of plan generation */
  generatedAt: string;
}

/**
 * Complete execution plan for vertical slice sequential execution.
 * Generated by Planner Agent, validated by Critic Agent.
 */
export interface ExecutionPlanV2 {
  /** Plan version identifier */
  version: 3;

  /** High-level summary of the architecture approach */
  architecturalSummary: string;

  /** Tech stack decisions for this project */
  techStack: TechStackV2;

  /** Ordered list of atomic execution steps */
  steps: PlannedStepV2[];

  /** Critic Agent's confidence score (0-100) */
  criticScore?: number;

  /** Critic Agent's identified risks */
  criticRisks?: string[];

  /** Planning metadata */
  metadata?: PlanningMetadataV2;
}

// ============================================================================
// STEP COMMIT
// ============================================================================

/**
 * Record of a successful step commit
 */
export interface StepCommit {
  /** Step index that was completed */
  stepIndex: number;

  /** Git commit hash */
  commitHash: string;

  /** Persona that executed the step */
  persona: WorkerPersona;

  /** Timestamp of commit */
  committedAt: string;

  /** Duration of step execution (ms) */
  durationMs?: number;
}

// ============================================================================
// PIPELINE STATE
// ============================================================================

/**
 * V2 Pipeline status (simplified from V1's 15+ statuses)
 */
export type PipelineV2Status = "planning" | "executing" | "done" | "failed";

/**
 * Step status for display
 */
export type StepStatus = "pending" | "in-progress" | "completed" | "failed";

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Calculate overall pipeline progress percentage
 */
export function calculateProgress(currentStepIndex: number, totalSteps: number): number {
  if (totalSteps === 0) return 0;
  return Math.round((currentStepIndex / totalSteps) * 100);
}

/**
 * Get step status based on current index and commit history
 */
export function getStepStatus(
  stepIndex: number,
  currentStepIndex: number,
  commitHistory: StepCommit[],
  taskStatus?: string
): StepStatus {
  // Check if step has a commit (completed)
  const hasCommit = commitHistory.some((c) => c.stepIndex === stepIndex);
  if (hasCommit) {
    return "completed";
  }

  // If task failed and this is the current step, it failed
  if (taskStatus === "failed" && stepIndex === currentStepIndex) {
    return "failed";
  }

  // If this is the current step and not completed, it's in progress
  if (stepIndex === currentStepIndex) {
    return "in-progress";
  }

  // Otherwise pending
  return "pending";
}

/**
 * Get status color for display
 */
export function getStatusColor(status: StepStatus): string {
  switch (status) {
    case "completed":
      return "text-green-500";
    case "in-progress":
      return "text-blue-500";
    case "failed":
      return "text-red-500";
    case "pending":
    default:
      return "text-gray-400";
  }
}

/**
 * Get status background color for display
 */
export function getStatusBgColor(status: StepStatus): string {
  switch (status) {
    case "completed":
      return "bg-green-500/20 border-green-500/50";
    case "in-progress":
      return "bg-blue-500/20 border-blue-500/50";
    case "failed":
      return "bg-red-500/20 border-red-500/50";
    case "pending":
    default:
      return "bg-gray-500/10 border-gray-500/30";
  }
}

/**
 * Format duration in ms to human readable
 */
export function formatDuration(ms: number | undefined): string {
  if (!ms) return "-";
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${Math.round(ms / 1000)}s`;
  return `${Math.round(ms / 60000)}m`;
}

/**
 * Format timestamp to time string
 */
export function formatTime(timestamp: string): string {
  const date = new Date(timestamp);
  return date.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
}

/**
 * Truncate commit hash for display
 */
export function truncateCommitHash(hash: string): string {
  return hash.substring(0, 7);
}

/**
 * Get complexity label
 */
export function getComplexityLabel(complexity: 1 | 2 | 3 | undefined): string {
  switch (complexity) {
    case 1:
      return "Low";
    case 2:
      return "Medium";
    case 3:
      return "High";
    default:
      return "Unknown";
  }
}

/**
 * Get complexity color
 */
export function getComplexityColor(complexity: 1 | 2 | 3 | undefined): string {
  switch (complexity) {
    case 1:
      return "text-green-500";
    case 2:
      return "text-yellow-500";
    case 3:
      return "text-red-500";
    default:
      return "text-gray-400";
  }
}
